root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ."
bin = "tmp/main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "ui"]
exclude_unchanged = true

log = "air.log"

poll = true
poll_interval = 500 # ms
delay = 500         # ms

# Stop running old binary when build errors occur.
stop_on_error = true

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
